---
version: '2.0'
services:
  wordpress:
    image: vitepress
    expose:
      - port: 80
        http_options:
          max_body_size: 104857600
        to:
          - global: true
profiles:
  compute:
    vitepress:
      resources:
        cpu:
          units: 1
        memory:
          size: 4Gi
        storage:
          - size: 4Gi
          - name: vitepress-data
            size: 32Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    akash:
      #######################################################
      #Keep this section to deploy on trusted providers
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      #######################################################
      #Remove this section to deploy on untrusted providers
      #Beware* You may have deployment, security, or other issues on untrusted providers
      #https://akash.network/docs/providers/audited-attributes
      pricing:
        vitepress:
          denom: uakt
          amount: 10000
deployment:
  vitepress:
    akash:
      profile: vitepress
      count: 1